"""Add worms_id and inaturalist_id to livestock

Revision ID: a2b79ad2fd7f
Revises: p7q8r9s0t1u2
Create Date: 2026-02-08 19:22:10.883461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2b79ad2fd7f'
down_revision: Union[str, None] = 'p7q8r9s0t1u2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('livestock', sa.Column('worms_id', sa.String(), nullable=True))
    op.add_column('livestock', sa.Column('inaturalist_id', sa.String(), nullable=True))
    op.add_column('livestock', sa.Column('cached_photo_url', sa.String(), nullable=True))
    op.create_index(op.f('ix_livestock_fishbase_species_id'), 'livestock', ['fishbase_species_id'], unique=False)
    op.create_index(op.f('ix_livestock_inaturalist_id'), 'livestock', ['inaturalist_id'], unique=False)
    op.create_index(op.f('ix_livestock_worms_id'), 'livestock', ['worms_id'], unique=False)
    op.create_index(op.f('ix_tank_events_user_id'), 'tank_events', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tank_events_user_id'), table_name='tank_events')
    op.drop_index(op.f('ix_livestock_worms_id'), table_name='livestock')
    op.drop_index(op.f('ix_livestock_inaturalist_id'), table_name='livestock')
    op.drop_index(op.f('ix_livestock_fishbase_species_id'), table_name='livestock')
    op.drop_column('livestock', 'cached_photo_url')
    op.drop_column('livestock', 'inaturalist_id')
    op.drop_column('livestock', 'worms_id')
    # ### end Alembic commands ###
