"""add consumables tables

Revision ID: ac13e0b88fe5
Revises: a1b2c3d4e5f6
Create Date: 2026-02-10 18:03:12.425865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'ac13e0b88fe5'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consumables',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('tank_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('consumable_type', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('product_name', sa.String(), nullable=True),
    sa.Column('quantity_on_hand', sa.Float(), nullable=True),
    sa.Column('quantity_unit', sa.String(), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('purchase_price', sa.String(), nullable=True),
    sa.Column('purchase_url', sa.String(), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tank_id'], ['tanks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consumables_consumable_type'), 'consumables', ['consumable_type'], unique=False)
    op.create_index(op.f('ix_consumables_id'), 'consumables', ['id'], unique=False)
    op.create_index(op.f('ix_consumables_name'), 'consumables', ['name'], unique=False)
    op.create_index(op.f('ix_consumables_status'), 'consumables', ['status'], unique=False)
    op.create_index(op.f('ix_consumables_tank_id'), 'consumables', ['tank_id'], unique=False)
    op.create_index(op.f('ix_consumables_user_id'), 'consumables', ['user_id'], unique=False)
    op.create_table('consumable_usage',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('consumable_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('usage_date', sa.Date(), nullable=False),
    sa.Column('quantity_used', sa.Float(), nullable=False),
    sa.Column('quantity_unit', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['consumable_id'], ['consumables.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consumable_usage_consumable_id'), 'consumable_usage', ['consumable_id'], unique=False)
    op.create_index(op.f('ix_consumable_usage_id'), 'consumable_usage', ['id'], unique=False)
    op.create_index(op.f('ix_consumable_usage_user_id'), 'consumable_usage', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_consumable_usage_user_id'), table_name='consumable_usage')
    op.drop_index(op.f('ix_consumable_usage_id'), table_name='consumable_usage')
    op.drop_index(op.f('ix_consumable_usage_consumable_id'), table_name='consumable_usage')
    op.drop_table('consumable_usage')
    op.drop_index(op.f('ix_consumables_user_id'), table_name='consumables')
    op.drop_index(op.f('ix_consumables_tank_id'), table_name='consumables')
    op.drop_index(op.f('ix_consumables_status'), table_name='consumables')
    op.drop_index(op.f('ix_consumables_name'), table_name='consumables')
    op.drop_index(op.f('ix_consumables_id'), table_name='consumables')
    op.drop_index(op.f('ix_consumables_consumable_type'), table_name='consumables')
    op.drop_table('consumables')
    # ### end Alembic commands ###
