"""add_status_and_removed_date_to_livestock

Revision ID: c51979ae1c4d
Revises: a2b79ad2fd7f
Create Date: 2026-02-08 21:03:09.567810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c51979ae1c4d'
down_revision: Union[str, None] = 'a2b79ad2fd7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('livestock', sa.Column('status', sa.String(), nullable=False, server_default='alive'))
    op.add_column('livestock', sa.Column('removed_date', sa.Date(), nullable=True))
    op.create_index(op.f('ix_livestock_status'), 'livestock', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_livestock_status'), table_name='livestock')
    op.drop_column('livestock', 'removed_date')
    op.drop_column('livestock', 'status')
    # ### end Alembic commands ###
