"""add_quantity_to_livestock

Revision ID: bb9fb0a6379d
Revises: c51979ae1c4d
Create Date: 2026-02-08 21:23:47.966312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb9fb0a6379d'
down_revision: Union[str, None] = 'c51979ae1c4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('livestock', sa.Column('quantity', sa.Integer(), nullable=False, server_default='1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('livestock', 'quantity')
    # ### end Alembic commands ###
